{"name": "Создать курьера", "status": "passed", "description": "Тест, который падает, по созданию рандомного курьера, где я перепробывал рандомные данные при которых мне отвечает система - такой курьер уже есть", "steps": [{"name": "создать рандомного курьера", "status": "passed", "start": 1730384249440, "stop": 1730384249830}], "start": 1730384249440, "stop": 1730384249830, "uuid": "ffc10e62-afa3-412d-9e73-dc9bc31533d9", "historyId": "f4975315a13e65adac1c16309d79d65a", "testCaseId": "f4975315a13e65adac1c16309d79d65a", "fullName": "tests.test_courier.TestCourierCreate#test_create_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "DESKTOP-OJ1AIB0"}, {"name": "thread", "value": "1172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}